name: Build and Push

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: heiths/ha-llm-tools

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, aarch64, armv7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Map architecture
        id: arch
        run: |
          case "${{ matrix.arch }}" in
            amd64) echo "platform=linux/amd64" >> $GITHUB_OUTPUT ;;
            aarch64) echo "platform=linux/arm64" >> $GITHUB_OUTPUT ;;
            armv7) echo "platform=linux/arm/v7" >> $GITHUB_OUTPUT ;;
          esac

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./ha-llm-tools
          platforms: ${{ steps.arch.outputs.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:3.20
            BUILD_ARCH=${{ matrix.arch }}